# Example

# Display a control or a screen box
add_subdirectory( compass )
add_subdirectory( label )
add_subdirectory( mapscale )
add_subdirectory( navigation )
add_subdirectory( overviewmap )

# Display geographical information on the map
add_subdirectory( graticule )
add_subdirectory( atmosphere )

