# Example

# Display a control or a screen box
add_subdirectory( compass )
add_subdirectory( license )
add_subdirectory( mapscale )
add_subdirectory( navigation )
add_subdirectory( overviewmap )
add_subdirectory( progress )

# Display geographical information on the map
add_subdirectory( crosshairs )
add_subdirectory( graticule )
add_subdirectory( atmosphere )

